version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: pysimplegui
    versions:
    - 4.34.0
    - 4.35.0
    - 4.36.0
    - 4.37.0
    - 4.38.0
    - 4.39.1
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  rebase-strategy: disabled
